export type ForbesAi50CompanySeed = {
  name: string;
  slug: string;
  website: string | null;
  oneLiner: string;
  funding: string;
  foundedYear: number;
  city: string;
  country: string;
  category: string;
  tags: string[];
};

export const FORBES_AI50_2026_SOURCE = {
  kind: "forbes_ai50",
  year: 2026,
  listName: "Forbes AI 50",
  url: "https://www.forbes.com/lists/ai50/",
} as const;

export const FORBES_AI50_2026_COMPANIES: ForbesAi50CompanySeed[] = [
  {
    name: "Abridge",
    slug: "abridge",
    website: "https://www.abridge.com",
    oneLiner: "AI notetaker for doctors",
    funding: "US$830M",
    foundedYear: 2018,
    city: "San Francisco",
    country: "United States",
    category: "Healthcare AI",
    tags: ["healthcare", "clinical documentation", "AI assistant"],
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    website: "https://www.anthropic.com",
    oneLiner: "AI models and products",
    funding: "US$60B",
    foundedYear: 2021,
    city: "San Francisco",
    country: "United States",
    category: "AI model provider",
    tags: ["foundation models", "AI assistant", "enterprise AI"],
  },
  {
    name: "Applied Intuition",
    slug: "applied-intuition",
    website: "https://www.appliedintuition.com",
    oneLiner: "Autonomous driving software",
    funding: "US$850M",
    foundedYear: 2017,
    city: "Sunnyvale",
    country: "United States",
    category: "Autonomous systems",
    tags: ["autonomous vehicles", "simulation", "mobility"],
  },
  {
    name: "Baseten",
    slug: "baseten",
    website: "https://www.baseten.co",
    oneLiner: "AI application deployment software",
    funding: "US$585M",
    foundedYear: 2019,
    city: "San Francisco",
    country: "United States",
    category: "AI infrastructure",
    tags: ["model serving", "inference", "developer tools"],
  },
  {
    name: "Black Forest Labs",
    slug: "black-forest-labs",
    website: "https://blackforestlabs.ai",
    oneLiner: "Image and video generation software",
    funding: "US$450M",
    foundedYear: 2024,
    city: "Freiburg",
    country: "Germany",
    category: "Generative media",
    tags: ["image generation", "video generation", "creative tools"],
  },
  {
    name: "Chai Discovery",
    slug: "chai-discovery",
    website: "https://www.chaidiscovery.com",
    oneLiner: "AI drug discovery",
    funding: "US$225M",
    foundedYear: 2024,
    city: "San Francisco",
    country: "United States",
    category: "Healthcare AI",
    tags: ["drug discovery", "biotech", "life sciences"],
  },
  {
    name: "Clay",
    slug: "clay",
    website: "https://www.clay.com",
    oneLiner: "AI go-to-market tools",
    funding: "US$204M",
    foundedYear: 2017,
    city: "New York",
    country: "United States",
    category: "Sales and marketing AI",
    tags: ["sales", "go-to-market", "data enrichment"],
  },
  {
    name: "Cognition",
    slug: "cognition",
    website: "https://cognition.ai",
    oneLiner: "AI coding agents",
    funding: "US$1B",
    foundedYear: 2024,
    city: "San Francisco",
    country: "United States",
    category: "Developer AI",
    tags: ["coding agents", "software engineering", "developer tools"],
  },
  {
    name: "Cohere",
    slug: "cohere",
    website: "https://cohere.com",
    oneLiner: "AI model development",
    funding: "US$1.6B",
    foundedYear: 2019,
    city: "Toronto",
    country: "Canada",
    category: "AI model provider",
    tags: ["foundation models", "enterprise AI", "language models"],
  },
  {
    name: "Crusoe",
    slug: "crusoe",
    website: "https://crusoe.ai",
    oneLiner: "AI data center builder",
    funding: "US$2.9B",
    foundedYear: 2018,
    city: "Denver",
    country: "United States",
    category: "AI infrastructure",
    tags: ["data centers", "cloud", "compute"],
  },
  {
    name: "Cursor",
    slug: "cursor",
    website: "https://cursor.com",
    oneLiner: "AI coding software",
    funding: "US$3.3B",
    foundedYear: 2022,
    city: "San Francisco",
    country: "United States",
    category: "Developer AI",
    tags: ["coding assistant", "software engineering", "developer tools"],
  },
  {
    name: "Cyera",
    slug: "cyera",
    website: "https://www.cyera.io",
    oneLiner: "Data security for AI",
    funding: "US$1.7B",
    foundedYear: 2021,
    city: "New York",
    country: "United States",
    category: "Security AI",
    tags: ["data security", "security", "governance"],
  },
  {
    name: "Databricks",
    slug: "databricks",
    website: "https://www.databricks.com",
    oneLiner: "Data storage and analytics",
    funding: "US$20B",
    foundedYear: 2013,
    city: "San Francisco",
    country: "United States",
    category: "Data infrastructure",
    tags: ["data warehouse", "analytics", "AI infrastructure"],
  },
  {
    name: "Decagon",
    slug: "decagon",
    website: "https://decagon.ai",
    oneLiner: "AI agents for customer service",
    funding: "US$481M",
    foundedYear: 2023,
    city: "San Francisco",
    country: "United States",
    category: "Customer support AI",
    tags: ["support", "AI agents", "customer service"],
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    website: "https://elevenlabs.io",
    oneLiner: "Voice generation software",
    funding: "US$800M",
    foundedYear: 2022,
    city: "New York",
    country: "United States",
    category: "Generative media",
    tags: ["voice generation", "audio", "creative tools"],
  },
  {
    name: "EliseAI",
    slug: "eliseai",
    website: "https://www.eliseai.com",
    oneLiner: "AI agents for housing and healthcare",
    funding: "US$392M",
    foundedYear: 2017,
    city: "New York",
    country: "United States",
    category: "Vertical AI",
    tags: ["housing", "healthcare", "AI agents"],
  },
  {
    name: "Fal",
    slug: "fal",
    website: "https://fal.ai",
    oneLiner: "Generative media infrastructure",
    funding: "US$330M",
    foundedYear: 2021,
    city: "San Francisco",
    country: "United States",
    category: "AI infrastructure",
    tags: ["inference", "generative media", "developer tools"],
  },
  {
    name: "Fireworks AI",
    slug: "fireworks-ai",
    website: "https://fireworks.ai",
    oneLiner: "AI application development software",
    funding: "US$327M",
    foundedYear: 2022,
    city: "San Mateo",
    country: "United States",
    category: "AI infrastructure",
    tags: ["model serving", "developer tools", "AI apps"],
  },
  {
    name: "Gamma",
    slug: "gamma",
    website: "https://gamma.app",
    oneLiner: "AI graphic design tools",
    funding: "US$91M",
    foundedYear: 2020,
    city: "San Francisco",
    country: "United States",
    category: "Productivity AI",
    tags: ["presentations", "design", "productivity"],
  },
  {
    name: "Genspark.ai",
    slug: "genspark-ai",
    website: "https://www.genspark.ai",
    oneLiner: "AI tools for knowledge workers",
    funding: "US$545M",
    foundedYear: 2023,
    city: "Palo Alto",
    country: "United States",
    category: "Productivity AI",
    tags: ["search", "knowledge work", "AI assistant"],
  },
  {
    name: "Glean",
    slug: "glean",
    website: "https://www.glean.com",
    oneLiner: "Enterprise search engine",
    funding: "US$770M",
    foundedYear: 2019,
    city: "Palo Alto",
    country: "United States",
    category: "Productivity AI",
    tags: ["enterprise search", "knowledge management", "workplace AI"],
  },
  {
    name: "Harvey",
    slug: "harvey",
    website: "https://www.harvey.ai",
    oneLiner: "Legal automation software",
    funding: "US$1B",
    foundedYear: 2022,
    city: "San Francisco",
    country: "United States",
    category: "Legal AI",
    tags: ["legal", "AI agents", "automation"],
  },
  {
    name: "HeyGen",
    slug: "heygen",
    website: "https://www.heygen.com",
    oneLiner: "AI video generation",
    funding: "US$74M",
    foundedYear: 2022,
    city: "Los Angeles",
    country: "United States",
    category: "Generative media",
    tags: ["video generation", "avatars", "creative tools"],
  },
  {
    name: "Krea",
    slug: "krea",
    website: "https://www.krea.ai",
    oneLiner: "Image generation software",
    funding: "US$83M",
    foundedYear: 2022,
    city: "San Francisco",
    country: "United States",
    category: "Generative media",
    tags: ["image generation", "design", "creative tools"],
  },
  {
    name: "Legora",
    slug: "legora",
    website: "https://www.legora.com",
    oneLiner: "Legal automation software",
    funding: "US$815M",
    foundedYear: 2023,
    city: "Stockholm",
    country: "Sweden",
    category: "Legal AI",
    tags: ["legal", "automation", "AI assistant"],
  },
  {
    name: "Listen Labs",
    slug: "listen-labs",
    website: "https://www.listenlabs.ai",
    oneLiner: "AI market research tools",
    funding: "US$100M",
    foundedYear: 2023,
    city: "San Francisco",
    country: "United States",
    category: "Research AI",
    tags: ["market research", "user research", "AI interviews"],
  },
  {
    name: "Lovable",
    slug: "lovable",
    website: "https://lovable.dev",
    oneLiner: "AI app and website builder",
    funding: "US$552M",
    foundedYear: 2023,
    city: "Stockholm",
    country: "Sweden",
    category: "Developer AI",
    tags: ["app builder", "website builder", "developer tools"],
  },
  {
    name: "Mercor",
    slug: "mercor",
    website: "https://mercor.com",
    oneLiner: "Data labeling service",
    funding: "US$483M",
    foundedYear: 2023,
    city: "San Francisco",
    country: "United States",
    category: "Data infrastructure",
    tags: ["data labeling", "AI training", "talent"],
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    website: "https://www.midjourney.com",
    oneLiner: "Image generation software",
    funding: "US$0M",
    foundedYear: 2021,
    city: "San Francisco",
    country: "United States",
    category: "Generative media",
    tags: ["image generation", "creative tools", "AI art"],
  },
  {
    name: "Mistral AI",
    slug: "mistral-ai",
    website: "https://mistral.ai",
    oneLiner: "Open source AI model development",
    funding: "US$3.1B",
    foundedYear: 2023,
    city: "Paris",
    country: "France",
    category: "AI model provider",
    tags: ["foundation models", "open source", "enterprise AI"],
  },
  {
    name: "Notion",
    slug: "notion",
    website: "https://www.notion.com",
    oneLiner: "Productivity software",
    funding: "US$330M",
    foundedYear: 2013,
    city: "San Francisco",
    country: "United States",
    category: "Productivity AI",
    tags: ["productivity", "workspace", "AI assistant"],
  },
  {
    name: "OpenAI",
    slug: "openai",
    website: "https://openai.com",
    oneLiner: "AI models and products",
    funding: "US$182.6B",
    foundedYear: 2015,
    city: "San Francisco",
    country: "United States",
    category: "AI model provider",
    tags: ["foundation models", "AI assistant", "developer platform"],
  },
  {
    name: "OpenEvidence",
    slug: "openevidence",
    website: "https://www.openevidence.com",
    oneLiner: "AI medical search",
    funding: "US$700M",
    foundedYear: 2022,
    city: "Miami",
    country: "United States",
    category: "Healthcare AI",
    tags: ["medical search", "healthcare", "clinical AI"],
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    website: "https://www.perplexity.ai",
    oneLiner: "AI search engine",
    funding: "US$1.7B",
    foundedYear: 2022,
    city: "San Francisco",
    country: "United States",
    category: "Search AI",
    tags: ["search", "AI assistant", "consumer AI"],
  },
  {
    name: "Physical Intelligence",
    slug: "physical-intelligence",
    website: "https://www.physicalintelligence.company",
    oneLiner: "AI models for robotics",
    funding: "US$1B",
    foundedYear: 2024,
    city: "San Francisco",
    country: "United States",
    category: "Robotics AI",
    tags: ["robotics", "foundation models", "embodied AI"],
  },
  {
    name: "Reflection",
    slug: "reflection",
    website: "https://reflection.ai",
    oneLiner: "Open source AI models",
    funding: "US$2.1B",
    foundedYear: 2024,
    city: "New York",
    country: "United States",
    category: "AI model provider",
    tags: ["foundation models", "open source", "enterprise AI"],
  },
  {
    name: "Replit",
    slug: "replit",
    website: "https://replit.com",
    oneLiner: "AI app and website builder",
    funding: "US$880M",
    foundedYear: 2016,
    city: "Foster City",
    country: "United States",
    category: "Developer AI",
    tags: ["developer tools", "app builder", "coding assistant"],
  },
  {
    name: "Rogo",
    slug: "rogo",
    website: "https://www.rogodata.com",
    oneLiner: "AI financial tools",
    funding: "US$150M",
    foundedYear: 2022,
    city: "New York",
    country: "United States",
    category: "Financial AI",
    tags: ["finance", "research", "AI assistant"],
  },
  {
    name: "Runway",
    slug: "runway",
    website: "https://runwayml.com",
    oneLiner: "Video and image editing software",
    funding: "US$860M",
    foundedYear: 2018,
    city: "New York",
    country: "United States",
    category: "Generative media",
    tags: ["video generation", "creative tools", "image editing"],
  },
  {
    name: "SambaNova",
    slug: "sambanova",
    website: "https://sambanova.ai",
    oneLiner: "AI chipmaker",
    funding: "US$1.5B",
    foundedYear: 2017,
    city: "San Jose",
    country: "United States",
    category: "AI infrastructure",
    tags: ["chips", "hardware", "AI infrastructure"],
  },
  {
    name: "Sierra",
    slug: "sierra",
    website: "https://sierra.ai",
    oneLiner: "AI agents for customer service",
    funding: "US$635M",
    foundedYear: 2023,
    city: "San Francisco",
    country: "United States",
    category: "Customer support AI",
    tags: ["support", "AI agents", "customer service"],
  },
  {
    name: "Skild AI",
    slug: "skild-ai",
    website: "https://www.skild.ai",
    oneLiner: "AI systems for robotics",
    funding: "US$2B",
    foundedYear: 2023,
    city: "Pittsburgh",
    country: "United States",
    category: "Robotics AI",
    tags: ["robotics", "foundation models", "embodied AI"],
  },
  {
    name: "Speak",
    slug: "speak",
    website: "https://www.speak.com",
    oneLiner: "AI language tutor",
    funding: "US$162M",
    foundedYear: 2016,
    city: "San Francisco",
    country: "United States",
    category: "Education AI",
    tags: ["language learning", "education", "consumer AI"],
  },
  {
    name: "Safe Superintelligence",
    slug: "safe-superintelligence",
    website: "https://ssi.inc",
    oneLiner: "AI research",
    funding: "US$3B",
    foundedYear: 2024,
    city: "Palo Alto",
    country: "United States",
    category: "AI model provider",
    tags: ["AI research", "foundation models", "safety"],
  },
  {
    name: "Suno",
    slug: "suno",
    website: "https://suno.com",
    oneLiner: "Music generation software",
    funding: "US$375M",
    foundedYear: 2022,
    city: "Cambridge",
    country: "United States",
    category: "Generative media",
    tags: ["music generation", "audio", "creative tools"],
  },
  {
    name: "Surge AI",
    slug: "surge-ai",
    website: "https://www.surgehq.ai",
    oneLiner: "Data labeling service",
    funding: "US$0M",
    foundedYear: 2020,
    city: "San Francisco",
    country: "United States",
    category: "Data infrastructure",
    tags: ["data labeling", "AI training", "human feedback"],
  },
  {
    name: "Synthesia",
    slug: "synthesia",
    website: "https://www.synthesia.io",
    oneLiner: "AI avatar and video generator",
    funding: "US$535M",
    foundedYear: 2017,
    city: "London",
    country: "United Kingdom",
    category: "Generative media",
    tags: ["video generation", "avatars", "enterprise video"],
  },
  {
    name: "Thinking Machines Lab",
    slug: "thinking-machines-lab",
    website: "https://thinkingmachines.ai",
    oneLiner: "AI research and products",
    funding: "US$2B",
    foundedYear: 2024,
    city: "San Francisco",
    country: "United States",
    category: "AI model provider",
    tags: ["AI research", "foundation models", "AI products"],
  },
  {
    name: "Together AI",
    slug: "together-ai",
    website: "https://www.together.ai",
    oneLiner: "AI cloud provider",
    funding: "US$548M",
    foundedYear: 2022,
    city: "San Francisco",
    country: "United States",
    category: "AI infrastructure",
    tags: ["cloud", "inference", "AI infrastructure"],
  },
  {
    name: "World Labs",
    slug: "world-labs",
    website: "https://www.worldlabs.ai",
    oneLiner: "Spatial AI model development",
    funding: "US$1B",
    foundedYear: 2023,
    city: "San Francisco",
    country: "United States",
    category: "Spatial AI",
    tags: ["spatial intelligence", "3D", "foundation models"],
  },
];
