export type YcCompany = {
  id: number;
  name: string;
  slug: string;
  former_names: string[];
  small_logo_thumb_url: string | null;
  website: string | null;
  all_locations: string | null;
  long_description: string | null;
  one_liner: string | null;
  team_size: number | null;
  highlight_black: boolean;
  highlight_latinx: boolean;
  highlight_women: boolean;
  industry: string | null;
  subindustry: string | null;
  launched_at: number | null;
  tags: string[];
  top_company: boolean;
  isHiring: boolean;
  nonprofit: boolean;
  batch: string | null;
  status: string | null;
  industries: string[];
  regions: string[];
  stage: string | null;
  app_video_public: boolean;
  demo_day_video_public: boolean;
  question_answers: boolean;
  url: string | null;
  api: string | null;
};

export type CompanyRecord = {
  id: number;
  name: string;
  slug: string | null;
  website: string | null;
  one_liner: string | null;
  long_description: string | null;
  batch: string | null;
  stage: string | null;
  industry: string | null;
  all_locations: string | null;
  launched_at: number | null;
  team_size: number | null;
  is_hiring: number;
  nonprofit: number;
  top_company: number;
  tags: string;
  industries: string;
  regions: string;
  url: string | null;
  small_logo_thumb_url: string | null;
  status: string | null;
};
